// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace System.Configuration
{
    public enum ConfigurationSaveMode
    {
        Modified = 0,
        //
        // Summary:
        //     Causes only properties that differ from inherited values to be written to the
        //     configuration file.
        Minimal = 1,
        //
        // Summary:
        //     Causes all properties to be written to the configuration file. This is useful
        //     mostly for creating information configuration files or moving configuration values
        //     from one machine to another.
        Full = 2
    }
}