// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace System.Configuration
{
    public sealed class ConfigurationElementProperty
    {
#pragma warning disable CS0824 // Constructor is marked external
        public extern ConfigurationElementProperty(ConfigurationValidatorBase validator);
#pragma warning restore CS0824 // Constructor is marked external

        //
        // Summary:
        //     Gets a System.Configuration.ConfigurationValidatorBase object used to validate
        //     the System.Configuration.ConfigurationElementProperty object.
        //
        // Returns:
        //     A System.Configuration.ConfigurationValidatorBase object.
        public ConfigurationValidatorBase Validator { get; }
    }
}