// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace System.Configuration
{
    public enum ConfigurationElementCollectionType
    {

        //
        // Summary:
        //     Collections of this type contain elements that apply to the level at which they
        //     are specified, and to all child levels. A child level cannot modify the properties
        //     specified by a parent element of this type.
        BasicMap = 0,
        //
        // Summary:
        //     The default type of System.Configuration.ConfigurationElementCollection. Collections
        //     of this type contain elements that can be merged across a hierarchy of configuration
        //     files. At any particular level within such a hierarchy, add, remove, and clear
        //     directives are used to modify any inherited properties and specify new ones.
        AddRemoveClearMap = 1,
        //
        // Summary:
        //     Same as System.Configuration.ConfigurationElementCollectionType.BasicMap, except
        //     that this type causes the System.Configuration.ConfigurationElementCollection
        //     object to sort its contents such that inherited elements are listed last.
        BasicMapAlternate = 2,
        //
        // Summary:
        //     Same as System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap,
        //     except that this type causes the System.Configuration.ConfigurationElementCollection
        //     object to sort its contents such that inherited elements are listed last.
        AddRemoveClearMapAlternate = 3
    }
}