// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.ComponentModel;

namespace System.Configuration
{
    public sealed class ConfigurationProperty
    {
#pragma warning disable CS0824 // Constructor is marked external
        public extern ConfigurationProperty(string name, Type type);
#pragma warning restore CS0824 // Constructor is marked external
        //
        // Summary:
        //     Initializes a new instance of the System.Configuration.ConfigurationProperty
        //     class.
        //
        // Parameters:
        //   name:
        //     The name of the configuration entity.
        //
        //   type:
        //     The type of the configuration entity.
        //
        //   defaultValue:
        //     The default value of the configuration entity.
#pragma warning disable CS0824 // Constructor is marked external
        public extern ConfigurationProperty(string name, Type type, object defaultValue);
#pragma warning restore CS0824 // Constructor is marked external
        //
        // Summary:
        //     Initializes a new instance of the System.Configuration.ConfigurationProperty
        //     class.
        //
        // Parameters:
        //   name:
        //     The name of the configuration entity.
        //
        //   type:
        //     The type of the configuration entity.
        //
        //   defaultValue:
        //     The default value of the configuration entity.
        //
        //   options:
        //     One of the System.Configuration.ConfigurationPropertyOptions enumeration values.
#pragma warning disable CS0824 // Constructor is marked external
        public extern ConfigurationProperty(string name, Type type, object defaultValue, ConfigurationPropertyOptions options);
#pragma warning restore CS0824 // Constructor is marked external

        //
        // Summary:
        //     Initializes a new instance of the System.Configuration.ConfigurationProperty
        //     class.
        //
        // Parameters:
        //   name:
        //     The name of the configuration entity.
        //
        //   type:
        //     The type of the configuration entity.
        //
        //   defaultValue:
        //     The default value of the configuration entity.
        //
        //   typeConverter:
        //     The type of the converter to apply.
        //
        //   validator:
        //     The validator to use.
        //
        //   options:
        //     One of the System.Configuration.ConfigurationPropertyOptions enumeration values.
#pragma warning disable CS0824 // Constructor is marked external
        public extern ConfigurationProperty(string name, Type type, object defaultValue, TypeConverter typeConverter, ConfigurationValidatorBase validator, ConfigurationPropertyOptions options);
#pragma warning restore CS0824 // Constructor is marked external
        //
        // Summary:
        //     Initializes a new instance of the System.Configuration.ConfigurationProperty
        //     class.
        //
        // Parameters:
        //   name:
        //     The name of the configuration entity.
        //
        //   type:
        //     The type of the configuration entity.
        //
        //   defaultValue:
        //     The default value of the configuration entity.
        //
        //   typeConverter:
        //     The type of the converter to apply.
        //
        //   validator:
        //     The validator to use.
        //
        //   options:
        //     One of the System.Configuration.ConfigurationPropertyOptions enumeration values.
        //
        //   description:
        //     The description of the configuration entity.
#pragma warning disable CS0824 // Constructor is marked external
        public extern ConfigurationProperty(string name, Type type, object defaultValue, TypeConverter typeConverter, ConfigurationValidatorBase validator, ConfigurationPropertyOptions options, string description);
#pragma warning restore CS0824 // Constructor is marked external

        //
        // Summary:
        //     Indicates whether the configuration property's parent configuration section is
        //     queried at serialization time to determine whether the configuration property
        //     should be serialized into XML.
        //
        // Returns:
        //     true if the parent configuration section should be queried; otherwise, false.
        public bool IsVersionCheckRequired { get; }
        //
        // Summary:
        //     Indicates whether the assembly name for the configuration property requires transformation
        //     when it is serialized for an earlier version of the .NET Framework.
        //
        // Returns:
        //     true if the property requires assembly name transformation; otherwise, false.
        public bool IsAssemblyStringTransformationRequired { get; }
        //
        // Summary:
        //     Indicates whether the type name for the configuration property requires transformation
        //     when it is serialized for an earlier version of the .NET Framework.
        //
        // Returns:
        //     true if the property requires type-name transformation; otherwise, false.
        public bool IsTypeStringTransformationRequired { get; }
        //
        // Summary:
        //     Gets a value that indicates whether the property is the default collection of
        //     an element.
        //
        // Returns:
        //     true if the property is the default collection of an element; otherwise, false.
        public bool IsDefaultCollection { get; }
        //
        // Summary:
        //     Gets a value indicating whether this System.Configuration.ConfigurationProperty
        //     is the key for the containing System.Configuration.ConfigurationElement object.
        //
        // Returns:
        //     true if this System.Configuration.ConfigurationProperty object is the key for
        //     the containing element; otherwise, false. The default is false.
        public bool IsKey { get; }
        //
        // Summary:
        //     Gets the default value for this System.Configuration.ConfigurationProperty property.
        //
        // Returns:
        //     An System.Object that can be cast to the type specified by the System.Configuration.ConfigurationProperty.Type
        //     property.
        public object DefaultValue { get; }
        //
        // Summary:
        //     Gets the System.ComponentModel.TypeConverter used to convert this System.Configuration.ConfigurationProperty
        //     into an XML representation for writing to the configuration file.
        //
        // Returns:
        //     A System.ComponentModel.TypeConverter used to convert this System.Configuration.ConfigurationProperty
        //     into an XML representation for writing to the configuration file.
        //
        // Exceptions:
        //   T:System.Exception:
        //     This System.Configuration.ConfigurationProperty cannot be converted.
        public TypeConverter Converter { get; }
        //
        // Summary:
        //     Gets the type of this System.Configuration.ConfigurationProperty object.
        //
        // Returns:
        //     A System.Type representing the type of this System.Configuration.ConfigurationProperty
        //     object.
        public Type Type { get; }
        //
        // Summary:
        //     Gets the description associated with the System.Configuration.ConfigurationProperty.
        //
        // Returns:
        //     A string value that describes the property.
        public string Description { get; }
        //
        // Summary:
        //     Gets the name of this System.Configuration.ConfigurationProperty.
        //
        // Returns:
        //     The name of the System.Configuration.ConfigurationProperty.
        public string Name { get; }
        //
        // Summary:
        //     Gets a value indicating whether this System.Configuration.ConfigurationProperty
        //     is required.
        //
        // Returns:
        //     true if the System.Configuration.ConfigurationProperty is required; otherwise,
        //     false. The default is false.
        public bool IsRequired { get; }
        //
        // Summary:
        //     Gets the System.Configuration.ConfigurationValidatorAttribute, which is used
        //     to validate this System.Configuration.ConfigurationProperty object.
        //
        // Returns:
        //     The System.Configuration.ConfigurationValidatorBase validator, which is used
        //     to validate this System.Configuration.ConfigurationProperty.
        public extern ConfigurationValidatorBase Validator { get; }
    }
}