// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace System.Configuration
{
    public enum ConfigurationPropertyOptions
    {
        None = 0,
        //
        // Summary:
        //     Indicates that the property is a default collection.
        IsDefaultCollection = 1,
        //
        // Summary:
        //     Indicates that the property is required.
        IsRequired = 2,
        //
        // Summary:
        //     Indicates that the property is a collection key.
        IsKey = 4,
        //
        // Summary:
        //     Indicates whether the type name for the configuration property requires transformation
        //     when it is serialized for an earlier version of the .NET Framework.
        IsTypeStringTransformationRequired = 8,
        //
        // Summary:
        //     Indicates whether the assembly name for the configuration property requires transformation
        //     when it is serialized for an earlier version of the .NET Framework.
        IsAssemblyStringTransformationRequired = 16,
        //
        // Summary:
        //     Indicates whether the configuration property's parent configuration section should
        //     be queried at serialization time to determine whether the configuration property
        //     should be serialized into XML.
        IsVersionCheckRequired = 32
    }
}