// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Configuration;

namespace BoDi
{
    public abstract class ContainerRegistrationCollection : ConfigurationElementCollection
    {
#pragma warning disable CS0824 // Constructor is marked external
        public extern ContainerRegistrationCollection();
#pragma warning restore CS0824 // Constructor is marked external

#pragma warning disable CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        public extern void Add(string implementationType, string interfaceType, string name = null);
#pragma warning restore CS0626 // Method, operator, or accessor is marked external and has no attributes on it
#pragma warning disable CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        protected extern override ConfigurationElement CreateNewElement();
#pragma warning restore CS0626 // Method, operator, or accessor is marked external and has no attributes on it
#pragma warning disable CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        protected extern override object GetElementKey(ConfigurationElement element);
#pragma warning restore CS0626 // Method, operator, or accessor is marked external and has no attributes on it
    }
}