// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace System.Configuration
{
    public sealed class ContextInformation
    {
        public object HostingContext { get; }
        //
        // Summary:
        //     Gets a value specifying whether the configuration property is being evaluated
        //     at the machine configuration level.
        //
        // Returns:
        //     true if the configuration property is being evaluated at the machine configuration
        //     level; otherwise, false.
        public bool IsMachineLevel { get; }


        //
        // Summary:
        //     Provides an object containing configuration-section information based on the
        //     specified section name.
        //
        // Parameters:
        //   sectionName:
        //     The name of the configuration section.
        //
        // Returns:
        //     An object containing the specified section within the configuration.
#pragma warning disable CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        public extern object GetSection(string sectionName);
#pragma warning restore CS0626 // Method, operator, or accessor is marked external and has no attributes on it
    }
}