// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections;

namespace System.Configuration
{
    public sealed class ElementInformation
    {
        public PropertyInformationCollection Properties { get; }
        //
        // Summary:
        //     Gets a value indicating whether the associated System.Configuration.ConfigurationElement
        //     object is in the configuration file.
        //
        // Returns:
        //     true if the associated System.Configuration.ConfigurationElement object is in
        //     the configuration file; otherwise, false.
        public bool IsPresent { get; }
        //
        // Summary:
        //     Gets a value that indicates whether the associated System.Configuration.ConfigurationElement
        //     object cannot be modified.
        //
        // Returns:
        //     true if the associated System.Configuration.ConfigurationElement object cannot
        //     be modified; otherwise, false.
        public bool IsLocked { get; }
        //
        // Summary:
        //     Gets a value indicating whether the associated System.Configuration.ConfigurationElement
        //     object is a System.Configuration.ConfigurationElementCollection collection.
        //
        // Returns:
        //     true if the associated System.Configuration.ConfigurationElement object is a
        //     System.Configuration.ConfigurationElementCollection collection; otherwise, false.
        public bool IsCollection { get; }
        //
        // Summary:
        //     Gets the source file where the associated System.Configuration.ConfigurationElement
        //     object originated.
        //
        // Returns:
        //     The source file where the associated System.Configuration.ConfigurationElement
        //     object originated.
        public string Source { get; }
        //
        // Summary:
        //     Gets the line number in the configuration file where the associated System.Configuration.ConfigurationElement
        //     object is defined.
        //
        // Returns:
        //     The line number in the configuration file where the associated System.Configuration.ConfigurationElement
        //     object is defined.
        public int LineNumber { get; }
        //
        // Summary:
        //     Gets the type of the associated System.Configuration.ConfigurationElement object.
        //
        // Returns:
        //     The type of the associated System.Configuration.ConfigurationElement object.
        public Type Type { get; }
        //
        // Summary:
        //     Gets the object used to validate the associated System.Configuration.ConfigurationElement
        //     object.
        //
        // Returns:
        //     The object used to validate the associated System.Configuration.ConfigurationElement
        //     object.
        public ConfigurationValidatorBase Validator { get; }
        //
        // Summary:
        //     Gets the errors for the associated element and subelements
        //
        // Returns:
        //     The collection containing the errors for the associated element and subelements
        public ICollection Errors { get; }
    }
}