// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TechTalk.SpecFlow.Plugins
{
    public class PluginDescriptor
    {
        public extern PluginDescriptor(string name, string path, PluginType type, string parameters);

        public string Name { get; }
        public string Path { get; }
        public PluginType Type { get; }
        public string Parameters { get; }
    }
}