// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
using System.ComponentModel;

namespace System.Configuration
{
    public sealed class PropertyInformation
    {
        public string Name { get; }
        //
        // Summary:
        //     Gets or sets an object containing the value related to a configuration attribute.
        //
        // Returns:
        //     An object containing the value for the System.Configuration.PropertyInformation
        //     object.
        public object Value { get; set; }
        //
        // Summary:
        //     Gets an object containing the default value related to a configuration attribute.
        //
        // Returns:
        //     An object containing the default value of the configuration attribute.
        public object DefaultValue { get; }
        //
        // Summary:
        //     Gets a System.Configuration.PropertyValueOrigin object related to the configuration
        //     attribute.
        //
        // Returns:
        //     A System.Configuration.PropertyValueOrigin object.
        public PropertyValueOrigin ValueOrigin { get; }
        //
        // Summary:
        //     Gets a value specifying whether the configuration attribute has been modified.
        //
        // Returns:
        //     true if the System.Configuration.PropertyInformation object has been modified;
        //     otherwise, false.
        public bool IsModified { get; }
        //
        // Summary:
        //     Gets a value specifying whether the configuration attribute is a key.
        //
        // Returns:
        //     true if the configuration attribute is a key; otherwise, false.
        public bool IsKey { get; }
        //
        // Summary:
        //     Gets a value specifying whether the configuration attribute is required.
        //
        // Returns:
        //     true if the System.Configuration.PropertyInformation object is required; otherwise,
        //     false.
        public bool IsRequired { get; }
        //
        // Summary:
        //     Gets a value specifying whether the configuration attribute is locked.
        //
        // Returns:
        //     true if the System.Configuration.PropertyInformation object is locked; otherwise,
        //     false.
        public bool IsLocked { get; }
        //
        // Summary:
        //     Gets the source file that corresponds to a configuration attribute.
        //
        // Returns:
        //     The source file of the System.Configuration.PropertyInformation object.
        public string Source { get; }
        //
        // Summary:
        //     Gets the line number in the configuration file related to the configuration attribute.
        //
        // Returns:
        //     A line number of the configuration file.
        public int LineNumber { get; }
        //
        // Summary:
        //     Gets the System.Type of the object that corresponds to a configuration attribute.
        //
        // Returns:
        //     The System.Type of the System.Configuration.PropertyInformation object.
        public Type Type { get; }
        //
        // Summary:
        //     Gets a System.Configuration.ConfigurationValidatorBase object related to the
        //     configuration attribute.
        //
        // Returns:
        //     A System.Configuration.ConfigurationValidatorBase object.
        public ConfigurationValidatorBase Validator { get; }
        //
        // Summary:
        //     Gets the System.ComponentModel.TypeConverter object related to the configuration
        //     attribute.
        //
        // Returns:
        //     A System.ComponentModel.TypeConverter object.
        public TypeConverter Converter { get; }
        //
        // Summary:
        //     Gets the description of the object that corresponds to a configuration attribute.
        //
        // Returns:
        //     The description of the configuration attribute.
        public string Description { get; }
    }
}