// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Specialized;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;

namespace System.Configuration
{
    public sealed class PropertyInformationCollection : NameObjectCollectionBase
    {
#pragma warning disable CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        public extern PropertyInformation this[string propertyName] { get; }
#pragma warning restore CS0626 // Method, operator, or accessor is marked external and has no attributes on it


        //
        // Summary:
        //     Copies the entire System.Configuration.PropertyInformationCollection collection
        //     to a compatible one-dimensional System.Array, starting at the specified index
        //     of the target array.
        //
        // Parameters:
        //   array:
        //     A one-dimensional System.Array that is the destination of the elements copied
        //     from the System.Configuration.PropertyInformationCollection collection. The System.Array
        //     must have zero-based indexing.
        //
        //   index:
        //     The zero-based index in array at which copying begins.
        //
        // Exceptions:
        //   T:System.ArgumentNullException:
        //     array is null.
        //
        //   T:System.ArgumentOutOfRangeException:
        //     The System.Array.Length property of array is less than System.Collections.Specialized.NameObjectCollectionBase.Count
        //     + index.
#pragma warning disable CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        public extern void CopyTo(PropertyInformation[] array, int index);
#pragma warning restore CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        //
        // Summary:
        //     Gets an System.Collections.IEnumerator object, which is used to iterate through
        //     this System.Configuration.PropertyInformationCollection collection.
        //
        // Returns:
        //     An System.Collections.IEnumerator object, which is used to iterate through this
        //     System.Configuration.PropertyInformationCollection.
        //[IteratorStateMachine(typeof(< GetEnumerator > d__8))]
#pragma warning disable CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        public extern override IEnumerator GetEnumerator();
#pragma warning restore CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        //
        // Summary:
        //     Populates a System.Runtime.Serialization.SerializationInfo object with the data
        //     needed to serialize the System.Configuration.PropertyInformationCollection instance.
        //
        // Parameters:
        //   info:
        //     A System.Runtime.Serialization.SerializationInfo object that contains the information
        //     required to serialize the System.Configuration.PropertyInformationCollection
        //     instance.
        //
        //   context:
        //     A System.Runtime.Serialization.StreamingContext object that contains the source
        //     and destination of the serialized stream associated with the System.Configuration.PropertyInformationCollection
        //     instance.
        //
        // Exceptions:
        //   T:System.ArgumentNullException:
        //     info is null.
#pragma warning disable CS0626 // Method, operator, or accessor is marked external and has no attributes on it
        public extern override void GetObjectData(SerializationInfo info, StreamingContext context);
#pragma warning restore CS0626 // Method, operator, or accessor is marked external and has no attributes on it
    }
}