// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace System.Configuration
{
    public enum PropertyValueOrigin
    {
        Default = 0,
        //
        // Summary:
        //     The configuration property value is inherited from a parent level in the configuration.
        Inherited = 1,
        //
        // Summary:
        //     The configuration property value is defined at the current level of the hierarchy.
        SetHere = 2
    }
}
